---
output: 
  html_document:
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Topic 1: Student's t test

### Exercise 

Edit the R code in the chunk below to add do a t test on the continuous variable miles per gallon (mpg) by transmission group (am, automatic or manual).
Note that you have to **replace** the placeholders cont_var (for continuous variable) and group_var (for grouping variable) in this code chunk.


<!---LEARNR EX 1--> 

<iframe style="margin:0 auto; min-width: 100%;" id="myIframe7" class="interactive"  src="https://pdrhiggins.shinyapps.io/learnr_app1/" scrolling="yes" frameborder="no"></iframe> 

<!-------------> 


### The t-distribution
Thus you can see the power of the mighty t test. William Sealy Gosset created it, and he is memorialized with a plaque at the Old Guiness Storehouse, where beer tours now are the primary business at this historical site. The plaque is not on the official tour, but can be found if you slip away from the tour and duck under some chains. Fortunately, most of the other tourists (and perhaps the tour guides) are usually well into their pints. For inexplicable reasons, the plaque with Gossett's name resembles a basketball with a green ring around it.

<script>
  iFrameResize({}, ".interactive");
</script>
